import { Poppins } from 'next/font/google';
import "../globals.css";
import Navbar from '@/components/global/Navbar';
import Footer from '@/components/global/Footer';
import ScrollableLinks from "@/components/global/ScrollableLinks";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const poppins = Poppins({
  weight: ['300', '400', '500', '700'], // Specify the weights to load
  subsets: ['latin'],
  display: 'swap',
});

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Navbar/>
        <ScrollableLinks/>
        {children}
        <Footer />
      </body>
    </html>
  );
}
