import { Poppins } from 'next/font/google';
import "../globals.css";
import PricingHeader from '@/components/global/PricingHeader';
import ProgressSteps from '@/components/global/ProgressSteps';


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const poppins = Poppins({
  weight: ['300', '400', '500', '700'], // Specify the weights to load
  subsets: ['latin'],
  display: 'swap',
});

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <PricingHeader />
        <ProgressSteps />
        {children}

      </body>
    </html>
  );
}
